### ISSUE TITLE
Redesign The Landing Page WIth Tailwind Css

### ISSUE THREAD

**Issue by AnushkJain2201** [AnushkJain2201/FrontEnd-iNoteBook#1]

**Comment by AnshulGoyal589** [comment]
i want to contribute in this under HacktoberFest 2023, please assign it to me

**Comment by AnushkJain2201** [comment]
@AnshulGoyal589  you are assigned for this task, complete the task and make a PR

**Comment by AnshulGoyal589** [comment]
I have added tailwind CSS in the application but i think there is some problem in backend part since an error is coming in sign up, so only login page and signup pages are accessible right now.
If still there is some issue in CSS part or you want to add some more CSS , please let me know.
I have understood whole codebase, if you want some more tailwind CSS in any other page, i would do it easily.

**Comment by AnushkJain2201** [comment]
@AnshulGoyal589 okay I will look into the issue, but now I Am merging your PR and closing this issue.

**Comment by AnshulGoyal589** [comment]
@AnushkJain2201 please add hactoberfest label in it since i want this PR to be counted in hactoberfest
